y_bows.dofile("compat", "bows")
y_bows.dofile("compat", "cucina_vegana")
y_bows.dofile("compat", "farming_redo")
y_bows.dofile("compat", "mesecons")
y_bows.dofile("compat", "projectile")
y_bows.dofile("compat", "x_bows")
