if not y_bows.settings.alias_x_bows then
	return
end

minetest.register_alias_force("x_bows:arrow_bronze", "y_bows:arrow_bronze")
minetest.register_alias_force("x_bows:arrow_bronze_node", "air")
minetest.register_alias_force("x_bows:arrow_diamond", "y_bows:arrow_diamond")
minetest.register_alias_force("x_bows:arrow_diamond_node", "air")
minetest.register_alias_force("x_bows:arrow_fire", "y_bows:arrow_fire")
minetest.register_alias_force("x_bows:arrow_fire_node", "air")
minetest.register_alias_force("x_bows:arrow_mese", "y_bows:arrow_mese")
minetest.register_alias_force("x_bows:arrow_mese_node", "air")
minetest.register_alias_force("x_bows:arrow_steel", "y_bows:arrow_steel")
minetest.register_alias_force("x_bows:arrow_steel_node", "air")
minetest.register_alias_force("x_bows:arrow_stone", "y_bows:arrow_stone")
minetest.register_alias_force("x_bows:arrow_stone_node", "air")
minetest.register_alias_force("x_bows:arrow_training_black", "y_bows:arrow_training_black")
minetest.register_alias_force("x_bows:arrow_training_black_node", "air")
minetest.register_alias_force("x_bows:arrow_training_blue", "y_bows:arrow_training_blue")
minetest.register_alias_force("x_bows:arrow_training_blue_node", "air")
minetest.register_alias_force("x_bows:arrow_training_brown", "y_bows:arrow_training_brown")
minetest.register_alias_force("x_bows:arrow_training_brown_node", "air")
minetest.register_alias_force("x_bows:arrow_training_cyan", "y_bows:arrow_training_cyan")
minetest.register_alias_force("x_bows:arrow_training_cyan_node", "air")
minetest.register_alias_force("x_bows:arrow_training_green", "y_bows:arrow_training_green")
minetest.register_alias_force("x_bows:arrow_training_green_node", "air")
minetest.register_alias_force("x_bows:arrow_training_grey", "y_bows:arrow_training_grey")
minetest.register_alias_force("x_bows:arrow_training_grey_node", "air")
minetest.register_alias_force("x_bows:arrow_training_magenta", "y_bows:arrow_training_magenta")
minetest.register_alias_force("x_bows:arrow_training_magenta_node", "air")
minetest.register_alias_force("x_bows:arrow_training_orange", "y_bows:arrow_training_orange")
minetest.register_alias_force("x_bows:arrow_training_orange_node", "air")
minetest.register_alias_force("x_bows:arrow_training_pink", "y_bows:arrow_training_pink")
minetest.register_alias_force("x_bows:arrow_training_pink_node", "air")
minetest.register_alias_force("x_bows:arrow_training_red", "y_bows:arrow_training_red")
minetest.register_alias_force("x_bows:arrow_training_red_node", "air")
minetest.register_alias_force("x_bows:arrow_training_violet", "y_bows:arrow_training_violet")
minetest.register_alias_force("x_bows:arrow_training_violet_node", "air")
minetest.register_alias_force("x_bows:arrow_training_white", "y_bows:arrow_training_white")
minetest.register_alias_force("x_bows:arrow_training_white_node", "air")
minetest.register_alias_force("x_bows:arrow_training_yellow", "y_bows:arrow_training_yellow")
minetest.register_alias_force("x_bows:arrow_training_yellow_node", "air")
minetest.register_alias_force("x_bows:arrow_wood", "y_bows:arrow_wood")
minetest.register_alias_force("x_bows:arrow_wood_node", "air")

minetest.register_alias_force("x_bows:ball_rock", "y_bows:ball_rock")
minetest.register_alias_force("x_bows:ball_rock_node", "air")

minetest.register_alias_force("x_bows:bow_steel", "y_bows:bow_steel")
minetest.register_alias_force("x_bows:bow_steel_charged", "y_bows:bow_steel")
minetest.register_alias_force("x_bows:bow_wood", "y_bows:bow_wood")
minetest.register_alias_force("x_bows:bow_wood_charged", "y_bows:bow_wood")

minetest.register_alias_force("x_bows:slingshot_steel", "y_bows:slingshot_steel")
minetest.register_alias_force("x_bows:slingshot_steel_charged", "y_bows:slingshot_steel")
minetest.register_alias_force("x_bows:slingshot_wood", "y_bows:slingshot_wood")
minetest.register_alias_force("x_bows:slingshot_wood_charged", "y_bows:slingshot_wood")

minetest.register_alias_force("x_bows:target", "y_bows:target")
